const DATA=JSON.parse(document.getElementById('guide-data').textContent),G=DATA.guide;
const $=id=>document.getElementById(id),esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const all=G.chronology;let position=0;
function code(b){const lines=DATA.sources[b.file].text.split('\n');return '<div class="code-box"><div class="code-head"><strong>'+esc(b.label)+'</strong><br>'+esc(b.file)+' · lines '+b.start+'–'+b.end+'</div><div class="code-scroll"><pre class="source">'+lines.slice(b.start-1,b.end).map((line,i)=>'<span class="line"><span class="num">'+(b.start+i)+'</span><span class="src">'+esc(line)+'</span></span>').join('')+'</pre></div></div>';}
function tab(name){if(!['start','overview','questions','talk','quiz'].includes(name))name='start';document.querySelectorAll('section.panel').forEach(p=>p.hidden=p.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.tab===name)));history.replaceState(null,'','#'+name+(name==='start'?'/'+position:''));}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));
function draw(){const item=all[position];$('start').innerHTML='<div class="journey-intro"><h2>Start at Main. Follow the calls. Return to the menu.</h2><p>Startup runs automatically. This teaching demo then chooses menu <strong>1 → 2 → 3 → 4</strong>. Only your selected option runs. A <strong>reference pause</strong> explains a definition used by the current block.</p><div class="path"><span>Main</span><span>→ sample objects</span><span>→ menu and rules</span><span>→ exit</span></div></div><div class="routebar"><button data-prev '+(position===0?'disabled':'')+'>← Previous</button><span>Block '+(position+1)+' of '+all.length+'</span><button data-next class="primary" '+(position===all.length-1?'disabled':'')+'>Next block →</button><label for="start-whole-select">Choose a code block</label><select id="start-whole-select">'+all.map((l,i)=>'<option value="'+i+'" '+(i===position?'selected':'')+'>'+(i+1)+'. '+esc(l.title)+'</option>').join('')+'</select></div><progress aria-label="Position in walkthrough" value="'+(position+1)+'" max="'+all.length+'"></progress><div class="kicker">'+esc(item.phase)+'</div><h2>'+esc(item.title)+'</h2><div class="trace"><div><strong>Before this block</strong><p>'+esc(item.before)+'</p></div><div><strong>After this block</strong><p>'+esc(item.after)+'</p></div></div><div class="step-grid"><div class="whole-code"><p class="block-comment"><strong>Teaching comment:</strong> '+esc(item.simple)+'</p>'+item.blocks.map(code).join('')+'</div><div class="explanation"><div class="kicker">What this block means</div><p class="plain">'+esc(item.simple)+'</p><ol class="steps">'+item.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol><div class="say"><div class="kicker">Say to the class</div><p>'+esc(item.say)+'</p></div><h3>Why this block belongs</h3><p>'+esc(item.why)+'</p><details><summary>The technical explanation</summary>'+item.technical.map(t=>'<p>'+esc(t)+'</p>').join('')+'</details><details><summary>Words and syntax</summary><dl class="terms">'+item.terms.map(t=>'<dt>'+esc(t[0])+'</dt><dd>'+esc(t[1])+'</dd>').join('')+'</dl></details></div></div><div class="after-code"><button data-prev '+(position===0?'disabled':'')+'>← Previous block</button> <button data-next class="primary" '+(position===all.length-1?'disabled':'')+'>Next block →</button></div>';$('start-whole-select').addEventListener('change',e=>move(Number(e.target.value)));$('start').querySelectorAll('[data-prev]').forEach(b=>b.addEventListener('click',()=>move(position-1)));$('start').querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>move(position+1)));}
function move(i){position=Math.max(0,Math.min(all.length-1,i));draw();tab('start');}
$('audience-questions').innerHTML=G.questions.map(q=>'<details><summary>'+esc(q.q)+'</summary><p class="say">'+esc(q.answer)+'</p><p>'+esc(q.technical)+'</p></details>').join('');
$('talk-blocks').innerHTML=all.map((l,i)=>'<article class="card"><h3>'+(i+1)+'. '+esc(l.title)+'</h3><p>'+esc(l.say)+'</p><button data-code="'+i+'">See this code</button></article>').join('');
document.querySelectorAll('[data-code]').forEach(b=>b.addEventListener('click',()=>move(Number(b.dataset.code))));
$('full-source').innerHTML=Object.entries(DATA.sources).map(([file,s])=>code({file,start:1,end:s.text.trimEnd().split('\n').length,label:file})).join('');
let seconds=480,timer=null,deadline=0;
function displayTimer(){$('timer').textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}
$('timer-start').onclick=()=>{if(timer){clearInterval(timer);timer=null;}else{deadline=Date.now()+seconds*1000;timer=setInterval(()=>{seconds=Math.max(0,Math.ceil((deadline-Date.now())/1000));displayTimer();if(!seconds){clearInterval(timer);timer=null;}},250);}};
$('timer-reset').onclick=()=>{clearInterval(timer);timer=null;seconds=480;displayTimer();};
const bank=[
 {q:'What is Project?',a:['A class that defines a project’s data and methods','One specific project object','A menu choice'],correct:0,why:'Project is the blueprint; new Project(...) creates an object.'},
 {q:'What does List<Project> projects mean?',a:['A method that creates a class','A variable named projects whose type is a list of Project objects','A single risk score'],correct:1,why:'List<Project> is the type; projects is the variable name.'},
 {q:'What does return do inside Main?',a:['Repeats the switch immediately','Creates a Project','Ends Main and this application'],correct:2,why:'break leaves a switch; return leaves the method.'},
 {q:'An open risk has likelihood 4 and impact 5. What does 20 mean?',a:['An 80% chance of failure','A priority score found by multiplying the ratings','The number of projects'],correct:1,why:'The score is a ranking, not a probability.'},
 {q:'What does string? allow?',a:['Text or null','Only numbers','A method with no result'],correct:0,why:'The question mark allows null; an empty string is still text.'},
 {q:'What does StatusTypes.cs contain?',a:['A class named StatusTypes','The program entry point','Two enums defining named choices'],correct:2,why:'A .cs extension means C# source, not necessarily a class.'}
];
let quizState={attempts:0,last:null,repeat:false},round=[],mc=0;
try{quizState=JSON.parse(localStorage.getItem('tracker-offline-quiz'))||quizState;}catch{}
function quizStatus(){$('quiz-status').textContent='Completed rounds: '+quizState.attempts+' · Last score: '+(quizState.last??'none')+(quizState.last===null?'':'%')+' · '+(quizState.repeat?'Repeat practice active until at least 90%.':'Target: at least 90%.');}
function startQuiz(){round=[...bank];for(let i=round.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[round[i],round[j]]=[round[j],round[i]];}round=round.slice(0,4);$('quiz-form').innerHTML=round.map((q,i)=>'<fieldset><legend>'+(i+1)+'. '+esc(q.q)+'</legend>'+q.a.map((a,j)=>'<label><input type="radio" name="q'+i+'" value="'+j+'"> '+esc(a)+'</label><br>').join('')+'</fieldset>').join('')+'<label for="written-answer"><strong>Written answer:</strong> Explain how private setters and ChangeStatus protect a project’s status.</label><textarea id="written-answer" rows="5" style="width:100%"></textarea>';$('written-review').hidden=true;$('quiz-submit').hidden=false;$('quiz-again').hidden=true;$('quiz-finish').disabled=false;$('quiz-result').textContent='';$('criterion-one').checked=false;$('criterion-two').checked=false;quizStatus();}
$('quiz-submit').onclick=()=>{const answers=round.map((q,i)=>document.querySelector('input[name="q'+i+'"]:checked'));if(answers.some(a=>!a)||!$('written-answer').value.trim()){$('quiz-result').textContent='Answer all four choices and the written question first.';return;}mc=answers.filter((a,i)=>Number(a.value)===round[i].correct).length;$('quiz-feedback').textContent='Multiple choice: '+mc+'/4. '+round.map(q=>q.why).join(' ');$('written-review').hidden=false;$('quiz-submit').hidden=true;$('quiz-result').textContent='';$('quiz-form').querySelectorAll('input,textarea').forEach(el=>el.disabled=true);};
$('quiz-finish').onclick=()=>{const score=Math.round((mc+Number($('criterion-one').checked)+Number($('criterion-two').checked))/6*100);quizState.attempts++;quizState.last=score;if(score<70)quizState.repeat=true;if(score>=90)quizState.repeat=false;try{localStorage.setItem('tracker-offline-quiz',JSON.stringify(quizState));}catch{}$('quiz-result').textContent='Score: '+score+'%. '+(quizState.repeat?'Review the code blocks, then repeat until at least 90%.':'Keep practicing your explanation aloud.');$('quiz-again').hidden=false;$('quiz-finish').disabled=true;quizStatus();};
$('quiz-again').onclick=startQuiz;startQuiz();
const initial=location.hash.slice(1).split('/');position=Math.max(0,Math.min(all.length-1,Number(initial[1])||0));draw();tab(initial[0]||'start');
